/**
 * Seed de sesiones bundleadas en catalog_sessions.
 *
 * Usa ON CONFLICT (id) DO NOTHING para no pisar registros existentes ni
 * sesiones creadas por usuarios (ids "usr_xxx").
 *
 * Ejecutar: pnpm --filter @workspace/scripts run seed:sessions
 */
import { db, pool, catalogSessionsTable } from "@workspace/db";

const SESSIONS = [
  // ── Meditaciones Guiadas ──────────────────────────────────────────────────
  {
    id: "1",
    title: "Adentro de uno mismo",
    subtitle: "Meditación Guiada",
    categoryId: "meditaciones-guiadas",
    categoryLabel: "Meditaciones",
    duration: 30,
    durationLabel: "30 min",
    description:
      "Un viaje guiado hacia el centro de tu ser. El sonido de los cuencos te acompaña suavemente mientras te sumerges en las capas más profundas de tu interior, encontrando quietud y claridad.",
    benefits: ["Relajación profunda", "Claridad mental", "Conexión interior", "Paz duradera"],
    instruments: ["Cuencos tibetanos", "Campana", "Voz guía"],
    meditationTag: "Visualizaciones",
    guideId: "sofia-ramirez",
  },
  {
    id: "5",
    title: "Más allá del sonido",
    subtitle: "Consejo del Día",
    categoryId: "meditaciones-guiadas",
    categoryLabel: "Meditaciones",
    meditationTag: "3 Minutos de Sabiduría",
    duration: 5,
    durationLabel: "5 min",
    description:
      "Una pequeña semilla de sabiduría para plantar en tu jornada. El sonido del cuenco abre el espacio, y la reflexión que le sigue puede cambiar el rumbo de tu día.",
    benefits: ["Inspiración diaria", "Intención clara", "Perspectiva fresca", "Momento de pausa"],
    instruments: ["Cuenco tibetano", "Voz guía"],
  },
  {
    id: "7",
    isPremium: true,
    title: "Prueba",
    subtitle: "Meditación Guiada",
    categoryId: "meditaciones-guiadas",
    categoryLabel: "Meditaciones",
    duration: 20,
    durationLabel: "20 min",
    description:
      "Una sesión de meditación guiada para explorar tu mundo interior. Los sonidos de cuencos tibetanos te acompañan en un viaje de atención plena y presencia consciente.",
    benefits: ["Relajación profunda", "Presencia plena", "Claridad mental", "Paz interior"],
    instruments: ["Cuencos tibetanos", "Voz guía", "Campanilla"],
    isNew: true,
    meditationTag: "Escaneo Corporal",
  },
  {
    id: "28",
    title: "Prueba 1",
    subtitle: "Meditación Guiada con Cuencos",
    categoryId: "meditaciones-guiadas",
    categoryLabel: "Meditaciones",
    duration: 10,
    durationLabel: "10 min",
    description:
      "Una meditación guiada con la voz de Casa del Cuenco acompañada de un fondo de cuencos tibetanos. Permítete soltar, respirar y volver a ti.",
    benefits: ["Calma profunda", "Presencia plena", "Conexión interior", "Relajación"],
    instruments: ["Cuencos tibetanos", "Voz guiada"],
    isNew: true,
    meditationTag: "Visualizaciones",
  },

  // ── Sonidos Ancestrales ────────────────────────────────────────────────────
  {
    id: "8",
    title: "Ondas Delta para Dormir",
    subtitle: "Sonidos Binaurales con Cuencos",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Cuencos Tibetanos",
    sleepTag: "Sonidos Binaurales",
    duration: 45,
    durationLabel: "45 min",
    description:
      "Frecuencias binaurales delta entretejidas con el canto de cuencos tibetanos. Tu cerebro es guiado suavemente hacia el estado de sueño más profundo y reparador.",
    benefits: ["Sueño profundo", "Reducción del estrés", "Regeneración celular", "Paz mental"],
    instruments: ["Cuencos tibetanos", "Frecuencias binaurales delta"],
    frequency: "Delta 1–4 Hz",
    isNew: true,
  },
  {
    id: "9",
    title: "Theta Profundo con Cuencos",
    subtitle: "Sonidos Binaurales con Cuencos",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Cuencos de Cuarzo",
    sleepTag: "Sonidos Binaurales",
    duration: 30,
    durationLabel: "30 min",
    description:
      "El estado theta es el umbral entre el sueño y la vigilia. Los cuencos y las frecuencias binaurales te llevan a ese espacio liminal donde surgen los sueños lúcidos y la intuición.",
    benefits: ["Creatividad expandida", "Sueños lúcidos", "Intuición profunda", "Relajación total"],
    instruments: ["Cuencos de cuarzo", "Frecuencias binaurales theta"],
    frequency: "Theta 4–8 Hz",
    isNew: true,
  },
  {
    id: "10",
    isPremium: true,
    title: "Sincronización Gamma 40Hz",
    subtitle: "Sonidos Binaurales con Cuencos",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Cuencos de Cuarzo",
    sleepTag: "Sonidos Binaurales",
    duration: 20,
    durationLabel: "20 min",
    description:
      "Las ondas gamma a 40Hz activan la lucidez y la integración neuronal. Combinadas con cuencos de alta frecuencia, esta sesión despierta tu claridad más elevada.",
    benefits: ["Claridad mental", "Foco profundo", "Integración neuronal", "Presencia total"],
    instruments: ["Cuencos de cuarzo soprano", "Frecuencias binaurales gamma"],
    frequency: "Gamma 40 Hz",
    isNew: true,
  },
  {
    id: "29",
    title: "Prueba Maestra 1",
    subtitle: "Cuencos Tibetanos",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    duration: 20,
    durationLabel: "20 min",
    description: "Esta es una prueba maestra.",
    benefits: ["Relajación profunda", "Calma interior", "Vibración ancestral", "Presencia plena"],
    instruments: ["Cuencos Tibetanos"],
    ancestralTag: "Cuencos Tibetanos",
    themeTag: ["Para la ansiedad"],
    sleepTag: "Sonidos Binaurales",
    isNew: true,
  },
  // Gongs
  {
    id: "71",
    title: "Gong del Templo Ancestral",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 30,
    durationLabel: "30 min",
    description:
      "El resonar profundo de un gong de bronce colgado en un templo milenario. Sus ondas atraviesan el cuerpo y disuelven la tensión acumulada, devolviendo el equilibrio.",
    benefits: ["Relajación profunda", "Liberación de tensión", "Presencia plena", "Equilibrio energético"],
    instruments: ["Gong de bronce", "Cuencos de acompañamiento"],
    isNew: true,
  },
  {
    id: "72",
    title: "Ola de Gong",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 45,
    durationLabel: "45 min",
    description:
      "Una ceremonia completa de baño de gong. Las ondas sonoras se expanden en círculos, envolviendo cada célula del cuerpo en vibración pura y sanadora.",
    benefits: ["Sanación vibracional", "Liberación emocional", "Profunda relajación", "Claridad mental"],
    instruments: ["Gong planetario", "Mallets de fieltro"],
    isNew: true,
  },
  {
    id: "73",
    title: "Mandala de Sonido",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 20,
    durationLabel: "20 min",
    description:
      "Los patrones grabados en la superficie del gong son un mandala que vibra con cada golpe. Una meditación visual y auditiva que centra la mente con precisión.",
    benefits: ["Concentración", "Armonía interior", "Claridad", "Conexión sagrada"],
    instruments: ["Gong de cobre cincelado", "Campanas tingsha"],
    isNew: true,
  },
  {
    id: "74",
    title: "Gong Lunar",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 35,
    durationLabel: "35 min",
    description:
      "Bajo la luna llena, el gong canta con la frecuencia del ciclo lunar. Una práctica de liberación y renovación alineada con los ritmos naturales de la Tierra.",
    benefits: ["Liberación", "Renovación", "Conexión con la naturaleza", "Sueño profundo"],
    instruments: ["Gong lunar", "Cuencos de cuarzo"],
    isNew: true,
  },
  {
    id: "75",
    title: "Círculo de Gongs",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 50,
    durationLabel: "50 min",
    description:
      "Múltiples gongs dispuestos en círculo crean un campo de sonido envolvente. Cada instrumento vibra en una frecuencia distinta, formando un tejido sonoro completo.",
    benefits: ["Inmersión total", "Relajación muscular profunda", "Paz interior", "Integración"],
    instruments: ["5 gongs planetarios", "Cuencos tibetanos"],
    isNew: true,
  },
  {
    id: "76",
    title: "Frecuencia del Gong",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 25,
    durationLabel: "25 min",
    description:
      "Cada gong planetario corresponde a un cuerpo celeste y su frecuencia. Esta sesión trabaja con las vibraciones del Sol y Júpiter para expandir la conciencia.",
    benefits: ["Expansión de conciencia", "Energía vital", "Optimismo", "Apertura"],
    instruments: ["Gong Solar", "Gong de Júpiter"],
    isNew: true,
  },
  {
    id: "77",
    title: "Gong del Himalaya",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 40,
    durationLabel: "40 min",
    description:
      "Forjado a mano en las montañas del Himalaya, este gong lleva siglos de tradición espiritual. Su voz grave y sostenida induce estados meditativos profundos.",
    benefits: ["Meditación profunda", "Silencio interior", "Conexión espiritual", "Arraigo"],
    instruments: ["Gong himalayo forjado a mano", "Cuencos de barro"],
    isNew: true,
  },
  {
    id: "78",
    title: "Gong Planetario",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 45,
    durationLabel: "45 min",
    description:
      "Los planetas emiten frecuencias que Hans Cousto calculó y trasladó al sonido. Esta sesión sintoniza el cuerpo con los ritmos del cosmos a través del gong.",
    benefits: ["Alineación cósmica", "Expansión", "Visión amplia", "Paz universal"],
    instruments: ["Gong planetario", "Platillos de cristal"],
    isNew: true,
  },
  {
    id: "79",
    title: "Resonancia en las Profundidades",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 30,
    durationLabel: "30 min",
    description:
      "Como las corrientes del océano que nunca vemos, la vibración del gong trabaja en capas profundas del sistema nervioso, liberando lo que el cuerpo ya no necesita.",
    benefits: ["Liberación del sistema nervioso", "Descanso profundo", "Soltar", "Fluidez"],
    instruments: ["Gong de agua", "Cuencos oceánicos"],
    isNew: true,
  },
  {
    id: "80",
    title: "Gong al Atardecer",
    subtitle: "Gongs",
    categoryId: "sonidos-ancestrales",
    categoryLabel: "Sesiones",
    ancestralTag: "Gongs",
    duration: 35,
    durationLabel: "35 min",
    description:
      "En muchas tradiciones el atardecer es el momento del gong: el día se cierra con gratitud y el cuerpo se prepara para el descanso. Una transición sonora hacia la noche.",
    benefits: ["Transición al descanso", "Gratitud", "Cierre del día", "Sueño reparador"],
    instruments: ["Gong de bronce", "Tambor frame"],
    isNew: true,
  },

  // ── Música y Sonidos ────────────────────────────────────────────────────────
  {
    id: "27",
    isPremium: true,
    title: "Riachuelo con Pájaros",
    subtitle: "Sonidos Naturales",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 10,
    durationLabel: "10 min",
    description:
      "El suave murmullo de un riachuelo de montaña acompañado por el canto de los pájaros. Un refugio sonoro que devuelve a la mente su ritmo natural, disuelve la tensión y abre el corazón a la presencia.",
    benefits: ["Calma instantánea", "Conexión con la naturaleza", "Reducción del estrés", "Presencia plena"],
    instruments: ["Agua corriente", "Canto de pájaros", "Ambiente natural"],
    isNew: true,
    sonidosTag: "Sonidos Naturaleza",
  },
  {
    id: "39",
    isPremium: true,
    title: "Tormenta Eléctrica",
    subtitle: "Atmósfera",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 50,
    durationLabel: "50 min",
    description:
      "El drama sonoro de una tormenta eléctrica lejana: truenos que reverberan, lluvia intensa y el silencio eléctrico entre relámpagos. Ideal para enfocarse o conciliar el sueño.",
    benefits: ["Concentración profunda", "Sueño reparador", "Presencia emocional", "Calma dramática"],
    instruments: ["Truenos", "Lluvia intensa", "Viento", "Silencio eléctrico"],
    sonidosTag: "Sonidos Atmosféricos",
    isNew: true,
  },
  {
    id: "40",
    isPremium: true,
    title: "Espacio Profundo",
    subtitle: "Atmósfera",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 60,
    durationLabel: "60 min",
    description:
      "Drones atmosféricos inspirados en los sonidos captados por la NASA del espacio profundo. Una experiencia de vastedad y silencio que disuelve los límites del yo.",
    benefits: ["Expansión de consciencia", "Perspectiva cósmica", "Meditación profunda", "Silencio interior"],
    instruments: ["Drones espaciales", "Texturas electrónicas", "Ruido blanco filtrado"],
    sonidosTag: "Sonidos Atmosféricos",
    isNew: true,
  },
  // Frecuencias (Música y Sonidos / Binaurales)
  {
    id: "23",
    isPremium: true,
    title: "Binaural Alpha 8Hz",
    subtitle: "Ondas Cerebrales",
    categoryId: "musica-sonidos",
    categoryLabel: "Frecuencias",
    duration: 30,
    durationLabel: "30 min",
    description:
      "Frecuencias binaurales en la banda Alpha (8–12 Hz). Ideal para estados de calma alerta, creatividad fluida y reducción de ansiedad. Usar con auriculares.",
    benefits: ["Estado alpha", "Creatividad", "Calma alerta", "Anti-estrés"],
    instruments: ["Frecuencias binaurales alpha", "Tono base suave"],
    isNew: true,
    frequency: "Alpha 8–12 Hz",
    soundTag: "Música Ambient",
  },
  {
    id: "24",
    isPremium: true,
    title: "Binaural Theta Nocturno",
    subtitle: "Ondas Cerebrales",
    categoryId: "musica-sonidos",
    categoryLabel: "Frecuencias",
    duration: 45,
    durationLabel: "45 min",
    description:
      "Frecuencias theta (4–8 Hz) para inducir estados de meditación profunda y sueño lúcido. Una transición suave hacia el descanso más reparador de tu noche.",
    benefits: ["Meditación profunda", "Sueño lúcido", "Creatividad nocturna", "Descanso total"],
    instruments: ["Frecuencias binaurales theta", "Ambiente nocturno"],
    isFeatured: true,
    isNew: true,
    frequency: "Theta 4–8 Hz",
    soundTag: "Música Ambient",
  },
  {
    id: "25",
    isPremium: true,
    title: "Música Ambient Dorada",
    subtitle: "Música Meditativa",
    categoryId: "musica-sonidos",
    categoryLabel: "Frecuencias",
    duration: 25,
    durationLabel: "25 min",
    description:
      "Capas de sintetizadores cálidos y cuencos de cuarzo crean una atmósfera dorada perfecta para meditar, leer o simplemente estar presente sin hacer nada.",
    benefits: ["Ambiente meditativo", "Foco suave", "Presencia sin esfuerzo", "Calma creativa"],
    instruments: ["Sintetizadores ambient", "Cuencos de cuarzo", "Pad armónico"],
    isNew: true,
    soundTag: "Música Ambient",
    artistId: "lumen-sonora",
  },
  {
    id: "26",
    isPremium: true,
    title: "Piano y Cuencos",
    subtitle: "Música Meditativa",
    categoryId: "musica-sonidos",
    categoryLabel: "Frecuencias",
    duration: 20,
    durationLabel: "20 min",
    description:
      "Notas de piano minimalistas entretejidas con el resonar de cuencos tibetanos. Una composición para abrir el corazón y soltar lo que ya no se necesita llevar.",
    benefits: ["Apertura emocional", "Claridad interior", "Calma profunda", "Bienestar general"],
    instruments: ["Piano acústico", "Cuencos tibetanos", "Silencio consciente"],
    isNew: true,
    soundTag: "Música Ambient",
    artistId: "raiz-profunda",
  },
  {
    id: "30",
    isPremium: true,
    title: "Prueba Maestra 2",
    subtitle: "Binaural",
    categoryId: "musica-sonidos",
    categoryLabel: "Frecuencias",
    duration: 20,
    durationLabel: "20 min",
    description: "Esta es una prueba maestra 2.",
    benefits: ["Energía matutina", "Claridad mental", "Activación suave", "Foco natural"],
    instruments: ["Binaural", "Sonido ambiente"],
    soundTag: "Música Ambient",
    themeTag: ["Energiza tus mañanas"],
    sleepTag: "ASMR Expansivos",
    isNew: true,
  },
  // Enteógena / Étnica
  {
    id: "31",
    isPremium: true,
    title: "Selva Enteógena",
    subtitle: "Música Enteógena",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 40,
    durationLabel: "40 min",
    description:
      "Una travesía sonora profunda inspirada en rituales amazónicos. Capas de percusión orgánica, drones y texturas enteógenas que disuelven la mente ordinaria y abren portales hacia lo invisible.",
    benefits: ["Expansión de consciencia", "Profundidad emocional", "Soltar el control", "Viaje interior"],
    instruments: ["Percusión ritual", "Drones", "Sintetizadores orgánicos"],
    soundTag: "Música Enteógena",
    artistId: "lumen-sonora",
    isNew: true,
  },
  {
    id: "32",
    isPremium: true,
    title: "Cacao Ceremonial",
    subtitle: "Música Enteógena",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 50,
    durationLabel: "50 min",
    description:
      "Composición diseñada para ceremonias de cacao: apertura del corazón, sentir la gratitud y conectar con la tierra. Un viaje musical que acompaña desde la apertura hasta la integración.",
    benefits: ["Apertura del corazón", "Gratitud", "Conexión con la tierra", "Integración"],
    instruments: ["Tambor chamánico", "Flautas nativas", "Texturas ambientales"],
    soundTag: "Música Enteógena",
    artistId: "raiz-profunda",
    isNew: true,
  },
  {
    id: "33",
    isPremium: true,
    title: "Cuencos del Alba",
    subtitle: "Música Étnica",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 30,
    durationLabel: "30 min",
    description:
      "Una composición musical que incorpora cuencos tibetanos, gongs y campanas ancestrales sobre una base ambient. Distinta a la práctica de cuencos: aquí los sonidos ancestrales son el lenguaje de una pieza musical continua.",
    benefits: ["Vibración profunda", "Limpieza energética", "Presencia plena", "Calma duradera"],
    instruments: ["Cuencos tibetanos", "Gongs de borde", "Campanas tingsha"],
    soundTag: "Música Étnica",
    isNew: true,
  },
  {
    id: "34",
    isPremium: true,
    title: "Didgeridoo y Tambor",
    subtitle: "Música Étnica",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 25,
    durationLabel: "25 min",
    description:
      "El resonar del didgeridoo se entrelaza con el pulso del tambor chamánico para crear un campo sonoro primitivo y poderoso. Música que ancla el cuerpo en la tierra y aquieta la mente.",
    benefits: ["Conexión con la tierra", "Anclaje corporal", "Calma mental", "Vibración ancestral"],
    instruments: ["Didgeridoo", "Tambor chamánico", "Ambiente natural"],
    soundTag: "Música Étnica",
    isNew: true,
  },
  // Sonidos Binaurales en musica-sonidos (Música)
  {
    id: "36",
    isPremium: true,
    title: "Gamma 40Hz — Claridad",
    subtitle: "Ondas Cerebrales",
    categoryId: "musica-sonidos",
    categoryLabel: "Música",
    duration: 30,
    durationLabel: "30 min",
    description:
      "Frecuencias Gamma (40 Hz) asociadas a estados de alta cognición, claridad mental y percepción expandida. Ideal para sesiones de estudio profundo o meditación activa.",
    benefits: ["Claridad mental", "Cognición elevada", "Foco intenso", "Percepción expandida"],
    instruments: ["Frecuencias binaurales gamma", "Tono base suave"],
    sonidosTag: "Sonidos Binaurales",
    isNew: true,
  },

  // ── Descanso — Relajaciones ──────────────────────────────────────────────
  {
    id: "41",
    title: "Soltar el día",
    subtitle: "Relajación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Relajaciones",
    duration: 20,
    durationLabel: "20 min",
    description:
      "Una relajación muscular progresiva que libera la tensión acumulada desde los pies hasta la cabeza, preparando el cuerpo para el descanso.",
    benefits: ["Liberación de tensión", "Relajación muscular", "Calma nerviosa", "Preparación para el sueño"],
    instruments: ["Voz guía", "Cuencos suaves", "Música de fondo"],
  },
  {
    id: "42",
    title: "Brisa nocturna",
    subtitle: "Relajación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Relajaciones",
    duration: 15,
    durationLabel: "15 min",
    description:
      "Deja que una brisa imaginaria recorra tu cuerpo disolviendo cada punto de tensión. Una práctica de relajación profunda con respiración consciente.",
    benefits: ["Respiración profunda", "Relajación instantánea", "Alivio del estrés", "Paz interior"],
    instruments: ["Voz guía", "Sonidos de brisa", "Cuencos de cristal"],
  },
  {
    id: "43",
    title: "Rendición total",
    subtitle: "Relajación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Relajaciones",
    duration: 25,
    durationLabel: "25 min",
    description: "Permítete rendirte por completo al descanso. Una guía de relajación profunda que invita a soltar el control y confiar en el cuerpo.",
    benefits: ["Rendición consciente", "Relajación total", "Reducción de ansiedad", "Sueño reparador"],
    instruments: ["Voz guía", "Drones suaves", "Campana tibetana"],
  },
  {
    id: "44",
    title: "Cuerpo de agua",
    subtitle: "Relajación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Relajaciones",
    duration: 18,
    durationLabel: "18 min",
    description:
      "Visualiza tu cuerpo convirtiéndose en agua tranquila. Una relajación profunda que disuelve los límites físicos y lleva la mente a la calma absoluta.",
    benefits: ["Disolución del estrés", "Relajación profunda", "Visualización guiada", "Calma mental"],
    instruments: ["Voz guía", "Sonidos de agua", "Cuencos tibetanos"],
  },
  {
    id: "45",
    title: "Noche estrellada",
    subtitle: "Relajación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Relajaciones",
    duration: 22,
    durationLabel: "22 min",
    description: "Bajo un cielo infinito de estrellas, la mente encuentra su quietud natural. Una relajación guiada con imágenes de la noche serena.",
    benefits: ["Expansión mental", "Relajación profunda", "Perspectiva cósmica", "Paz nocturna"],
    instruments: ["Voz guía", "Texturas espaciales", "Cuencos suaves"],
  },

  // ── Descanso — Sueño profundo ─────────────────────────────────────────────
  {
    id: "47",
    title: "Umbral del sueño",
    subtitle: "Sueño profundo",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Sueño profundo",
    duration: 30,
    durationLabel: "30 min",
    description:
      "Una transición suave desde la vigilia hasta el sueño profundo, guiando la mente a través del umbral hipnagógico con sonidos graduales.",
    benefits: ["Inicio del sueño", "Transición suave", "Relajación progresiva", "Descanso reparador"],
    instruments: ["Cuencos tibetanos", "Frecuencias theta", "Voz guía suave"],
  },
  {
    id: "48",
    title: "Mar sin orillas",
    subtitle: "Sueño profundo",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Sueño profundo",
    duration: 60,
    durationLabel: "60 min",
    description:
      "El sonido continuo del océano profundo acompaña la mente hacia las capas más oscuras y tranquilas del sueño. Una inmersión total en el descanso.",
    benefits: ["Sueño sin interrupciones", "Calma profunda", "Reducción del ruido mental", "Descanso oceánico"],
    instruments: ["Olas del océano", "Frecuencias delta", "Ruido blanco suave"],
  },
  {
    id: "49",
    title: "Cueva de cristal",
    subtitle: "Sueño profundo",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Sueño profundo",
    duration: 40,
    durationLabel: "40 min",
    description:
      "El resonar de los cuencos de cuarzo en un espacio interior imaginario lleva el sistema nervioso al reposo más completo y profundo.",
    benefits: ["Resonancia profunda", "Sueño reparador", "Desconexión mental", "Calma absoluta"],
    instruments: ["Cuencos de cuarzo", "Reverberación espacial", "Drones graves"],
  },
  {
    id: "50",
    title: "Noche sin pensamientos",
    subtitle: "Sueño profundo",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Sueño profundo",
    duration: 50,
    durationLabel: "50 min",
    description:
      "Diseñada específicamente para quienes luchan contra la mente activa al dormir. Frecuencias y guía que disuelven el flujo de pensamientos nocturnos.",
    benefits: ["Silencio mental", "Descanso profundo", "Liberación de preocupaciones", "Inicio rápido del sueño"],
    instruments: ["Frecuencias delta", "Voz guía", "Cuencos tibetanos"],
  },

  // ── Descanso — Ruidos ─────────────────────────────────────────────────────
  {
    id: "51",
    title: "Lluvia en el bosque",
    subtitle: "Ruidos",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Ruidos",
    duration: 60,
    durationLabel: "60 min",
    description:
      "El sonido continuo de la lluvia sobre las hojas del bosque crea un manto sonoro perfecto para enmascarar el entorno y facilitar el sueño.",
    benefits: ["Enmascaramiento de ruido", "Relajación natural", "Ambiente acogedor", "Sueño continuo"],
    instruments: ["Lluvia", "Bosque", "Truenos lejanos"],
  },
  {
    id: "52",
    title: "Ruido blanco puro",
    subtitle: "Ruidos",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Ruidos",
    duration: 60,
    durationLabel: "60 min",
    description:
      "Ruido blanco puro de alta calidad que bloquea las distracciones sonoras del entorno y crea el ambiente ideal para el sueño o la concentración.",
    benefits: ["Bloqueo de ruido", "Concentración", "Sueño sin interrupciones", "Ambiente neutro"],
    instruments: ["Ruido blanco"],
  },
  {
    id: "53",
    title: "Olas del Pacífico",
    subtitle: "Ruidos",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Ruidos",
    duration: 60,
    durationLabel: "60 min",
    description:
      "El ritmo hipnótico de las olas del océano Pacífico rompiendo suavemente en la orilla. Un sonido ancestral que sincroniza la respiración con el mar.",
    benefits: ["Ritmo natural", "Relajación instantánea", "Respiración sincronizada", "Sueño profundo"],
    instruments: ["Olas del océano", "Brisa marina"],
  },
  {
    id: "54",
    title: "Arroyo en la montaña",
    subtitle: "Ruidos",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Ruidos",
    duration: 45,
    durationLabel: "45 min",
    description:
      "El fluir constante de un arroyo de montaña entre piedras crea un ruido rosa natural que calma el sistema nervioso y facilita el descanso.",
    benefits: ["Ruido rosa natural", "Calma nerviosa", "Ambiente natural", "Sueño tranquilo"],
    instruments: ["Arroyo", "Pájaros lejanos", "Viento suave"],
  },
  {
    id: "55",
    title: "Ventilador nocturno",
    subtitle: "Ruidos",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Ruidos",
    duration: 60,
    durationLabel: "60 min",
    description:
      "El zumbido constante y familiar de un ventilador de techo. Un ruido de fondo reconfortante que muchas personas asocian con el sueño tranquilo.",
    benefits: ["Ambiente familiar", "Enmascaramiento suave", "Sueño continuo", "Temperatura sonora"],
    instruments: ["Ventilador", "Ruido de fondo suave"],
  },

  // ── Descanso — Meditaciones ───────────────────────────────────────────────
  {
    id: "56",
    title: "Escaneo para dormir",
    subtitle: "Meditación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Meditaciones",
    duration: 20,
    durationLabel: "20 min",
    description:
      "Un escaneo corporal completo diseñado para el momento de acostarse. Recorre cada parte del cuerpo soltando tensión y preparando el sistema para el sueño.",
    benefits: ["Relajación corporal", "Sueño reparador", "Consciencia somática", "Preparación para dormir"],
    instruments: ["Voz guía", "Música suave", "Cuencos tibetanos"],
  },
  {
    id: "57",
    title: "Respiración 4-7-8",
    subtitle: "Meditación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Meditaciones",
    duration: 10,
    durationLabel: "10 min",
    description:
      "La técnica de respiración 4-7-8 del Dr. Andrew Weil, guiada con sonidos de cuencos. Activa el sistema nervioso parasimpático en minutos.",
    benefits: ["Activación parasimpática", "Reducción de ansiedad", "Inicio rápido del sueño", "Regulación nerviosa"],
    instruments: ["Voz guía", "Cuencos tibetanos"],
  },
  {
    id: "58",
    title: "Gratitud nocturna",
    subtitle: "Meditación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Meditaciones",
    duration: 15,
    durationLabel: "15 min",
    description:
      "Cierra el día con una meditación de gratitud que transforma las preocupaciones en reconocimiento y lleva el corazón a la paz antes de dormir.",
    benefits: ["Gratitud consciente", "Paz nocturna", "Cierre del día", "Bienestar emocional"],
    instruments: ["Voz guía", "Cuencos suaves", "Música de fondo"],
  },
  {
    id: "59",
    title: "Yoga Nidra",
    subtitle: "Meditación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Meditaciones",
    duration: 35,
    durationLabel: "35 min",
    description:
      "Una sesión completa de Yoga Nidra, el sueño yóguico consciente. Guía el cuerpo al borde del sueño mientras la mente permanece en una consciencia suave.",
    benefits: ["Estado hipnagógico", "Descanso profundo", "Consciencia expandida", "Sueño consciente"],
    instruments: ["Voz guía", "Cuencos tibetanos", "Frecuencias theta"],
  },
  {
    id: "60",
    title: "Soltar el mañana",
    subtitle: "Meditación",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Meditaciones",
    duration: 12,
    durationLabel: "12 min",
    description:
      "Una meditación para quienes se van a dormir con preocupaciones sobre el futuro. Suelta el mañana, confía en el proceso y descansa en el presente.",
    benefits: ["Liberación del futuro", "Confianza", "Presente nocturno", "Sueño tranquilo"],
    instruments: ["Voz guía", "Cuencos suaves"],
  },

  // ── Descanso — Historias para dormir ─────────────────────────────────────
  {
    id: "61",
    title: "El jardín de la luna",
    subtitle: "Historia para dormir",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias para dormir",
    skipDetail: true,
    duration: 25,
    durationLabel: "25 min",
    description:
      "Un relato contemplativo sobre un jardín que solo florece bajo la luna llena. Una historia de belleza silenciosa y calma absoluta para el descanso.",
    benefits: ["Escape mental", "Relajación profunda", "Imágenes tranquilas", "Sueño inducido"],
    instruments: ["Voz narradora", "Música de fondo", "Sonidos de naturaleza"],
  },
  {
    id: "62",
    title: "La cabaña en la niebla",
    subtitle: "Historia para dormir",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias para dormir",
    skipDetail: true,
    duration: 30,
    durationLabel: "30 min",
    description:
      "Una historia de regreso al hogar: una cabaña cálida en medio de un bosque silencioso. Un relato lento y reconfortante perfecto para cerrar los ojos.",
    benefits: ["Sensación de hogar", "Calma profunda", "Escape narrativo", "Sueño tranquilo"],
    instruments: ["Voz narradora", "Chimenea", "Lluvia suave"],
  },
  {
    id: "63",
    title: "Viaje en tren nocturno",
    subtitle: "Historia para dormir",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias para dormir",
    skipDetail: true,
    duration: 28,
    durationLabel: "28 min",
    description:
      "A bordo de un tren que cruza paisajes nocturnos, el ritmo constante de las ruedas sobre los rieles hipnotiza y lleva la mente al descanso total.",
    benefits: ["Ritmo hipnótico", "Paisajes imaginados", "Relajación gradual", "Sueño profundo"],
    instruments: ["Voz narradora", "Sonido de tren", "Música suave"],
  },
  {
    id: "64",
    title: "La orilla al amanecer",
    subtitle: "Historia para dormir",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias para dormir",
    skipDetail: true,
    duration: 22,
    durationLabel: "22 min",
    description:
      "Una historia de contemplación en la orilla del mar antes del amanecer. La soledad tranquila del agua y la brisa conducen a un descanso total.",
    benefits: ["Contemplación serena", "Presencia total", "Relajación natural", "Inicio del sueño"],
    instruments: ["Voz narradora", "Olas del mar", "Pájaros lejanos"],
  },
  {
    id: "65",
    title: "El templo del silencio",
    subtitle: "Historia para dormir",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias para dormir",
    skipDetail: true,
    duration: 35,
    durationLabel: "35 min",
    description:
      "Un viaje narrativo a un templo antiguo donde el silencio es la única práctica. Una historia lenta y profunda que invita al descanso sin esfuerzo.",
    benefits: ["Silencio interior", "Relajación profunda", "Escape espiritual", "Sueño reparador"],
    instruments: ["Voz narradora", "Cuencos tibetanos", "Silencio"],
  },

  // ── Descanso — Historias infantiles ──────────────────────────────────────
  {
    id: "66",
    title: "La nube viajera",
    subtitle: "Historia infantil",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias infantiles",
    skipDetail: true,
    duration: 15,
    durationLabel: "15 min",
    description: "Una pequeña nube que viaja por el cielo buscando el lugar perfecto para descansar. Un cuento suave y entrañable para los más pequeños.",
    benefits: ["Imaginación tranquila", "Sueño infantil", "Calma nocturna", "Mundo de sueños"],
    instruments: ["Voz narradora", "Música de cuna", "Sonidos suaves"],
  },
  {
    id: "67",
    title: "El guardián de las estrellas",
    subtitle: "Historia infantil",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias infantiles",
    skipDetail: true,
    duration: 18,
    durationLabel: "18 min",
    description: "Un viejito sabio cuida las estrellas cada noche para que brillen mientras los niños duermen. Un cuento mágico lleno de ternura y calma.",
    benefits: ["Seguridad nocturna", "Imaginación dulce", "Sueño tranquilo", "Mundo mágico"],
    instruments: ["Voz narradora", "Música de caja de música", "Campanas suaves"],
  },
  {
    id: "68",
    title: "El río de los sueños",
    subtitle: "Historia infantil",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias infantiles",
    skipDetail: true,
    duration: 20,
    durationLabel: "20 min",
    description:
      "Todos los sueños del mundo viajan por un río invisible. Esta noche, es tu turno de subir a la barca y dejarte llevar hacia aventuras increíbles.",
    benefits: ["Imaginación activa", "Transición al sueño", "Mundo onírico", "Calma nocturna"],
    instruments: ["Voz narradora", "Sonidos de río", "Música suave"],
  },
  {
    id: "69",
    title: "La tortuga lenta",
    subtitle: "Historia infantil",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias infantiles",
    skipDetail: true,
    duration: 12,
    durationLabel: "12 min",
    description:
      "Una tortuga sabia enseña a los animales del bosque el arte de ir despacio y descansar bien. Un cuento sobre la calma y el poder del silencio.",
    benefits: ["Ritmo lento", "Calma aprendida", "Sueño precoz", "Valores tranquilos"],
    instruments: ["Voz narradora", "Sonidos del bosque", "Música tranquila"],
  },
  {
    id: "70",
    title: "Las semillas duermen",
    subtitle: "Historia infantil",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "Historias infantiles",
    skipDetail: true,
    duration: 14,
    durationLabel: "14 min",
    description:
      "Bajo la tierra, las semillas descansan en la oscuridad antes de convertirse en flores. Un cuento sobre el poder transformador del descanso nocturno.",
    benefits: ["Metáfora del descanso", "Calma nocturna", "Sueño natural", "Crecimiento interior"],
    instruments: ["Voz narradora", "Sonidos de naturaleza", "Música de cuna"],
  },

  // ── Descanso — ASMR ───────────────────────────────────────────────────────
  {
    id: "81",
    title: "Susurros de medianoche",
    subtitle: "ASMR",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "ASMR",
    skipDetail: true,
    duration: 20,
    durationLabel: "20 min",
    description:
      "Susurros suaves y cercanos que activan la respuesta sensorial del cuerpo, disolviendo la tensión hasta llevarte al sueño.",
    benefits: ["Relajación sensorial", "Calma inmediata", "Sueño inducido", "Desconexión mental"],
    instruments: ["Voz susurrada", "Micrófono binaural"],
    isNew: true,
  },
  {
    id: "82",
    title: "Sonidos de papel y tela",
    subtitle: "ASMR",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "ASMR",
    skipDetail: true,
    duration: 18,
    durationLabel: "18 min",
    description:
      "El roce del papel, la tela y los objetos cotidianos crean una capa de sonido íntimo que relaja el sistema nervioso poco a poco.",
    benefits: ["Estímulo sensorial suave", "Relajación progresiva", "Foco tranquilo", "Sueño natural"],
    instruments: ["Papel", "Tela", "Objetos táctiles"],
    isNew: true,
  },
  {
    id: "83",
    title: "Tapping nocturno",
    subtitle: "ASMR",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "ASMR",
    skipDetail: true,
    duration: 22,
    durationLabel: "22 min",
    description:
      "Golpecitos rítmicos y suaves sobre distintas superficies generan una vibración hipnótica que acompaña el cuerpo hacia el descanso.",
    benefits: ["Ritmo hipnótico", "Relajación muscular", "Calma auditiva", "Sueño profundo"],
    instruments: ["Tapping", "Superficies de madera y vidrio"],
  },
  {
    id: "84",
    title: "Agua y cristales",
    subtitle: "ASMR",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "ASMR",
    skipDetail: true,
    duration: 25,
    durationLabel: "25 min",
    description:
      "El sonido del agua fluyendo entre cristales crea una textura sonora envolvente, íntima y profundamente relajante.",
    benefits: ["Textura envolvente", "Relajación profunda", "Escape sensorial", "Sueño reparador"],
    instruments: ["Agua", "Cristales", "Cuencos de cuarzo"],
  },
  {
    id: "85",
    title: "Cepillado relajante",
    subtitle: "ASMR",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "ASMR",
    skipDetail: true,
    duration: 16,
    durationLabel: "16 min",
    description:
      "El sonido suave y repetitivo del cepillado activa una respuesta de calma inmediata en el cuerpo, ideal para conciliar el sueño.",
    benefits: ["Respuesta de calma", "Relajación inmediata", "Desconexión sensorial", "Sueño rápido"],
    instruments: ["Cepillos", "Susurros suaves"],
  },
  {
    id: "86",
    title: "Voz cercana",
    subtitle: "ASMR",
    categoryId: "descanso",
    categoryLabel: "Dormir",
    descansoTag: "ASMR",
    skipDetail: true,
    duration: 24,
    durationLabel: "24 min",
    description:
      "Una voz cercana y pausada que acompaña con palabras suaves, creando una sensación de compañía tranquila antes de dormir.",
    benefits: ["Compañía tranquila", "Relajación auditiva", "Calma emocional", "Sueño acompañado"],
    instruments: ["Voz cercana", "Ambiente silencioso"],
  },
] as const;

async function main() {
  console.log(`Sembrando ${SESSIONS.length} sesiones bundleadas...`);

  let inserted = 0;
  let skipped = 0;

  for (const session of SESSIONS) {
    const result = await db
      .insert(catalogSessionsTable)
      .values({
        id: session.id,
        title: session.title,
        subtitle: session.subtitle,
        categoryId: session.categoryId,
        categoryLabel: session.categoryLabel,
        duration: session.duration,
        durationLabel: session.durationLabel,
        description: session.description,
        benefits: [...(session.benefits as readonly string[])],
        instruments: "instruments" in session ? [...(session.instruments as readonly string[])] : [],
        isFeatured: "isFeatured" in session ? Boolean(session.isFeatured) : false,
        isNew: "isNew" in session ? Boolean(session.isNew) : false,
        isPremium: "isPremium" in session ? Boolean(session.isPremium) : false,
        skipDetail: "skipDetail" in session ? Boolean(session.skipDetail) : false,
        skipMiniPlayer: "skipMiniPlayer" in session ? Boolean((session as any).skipMiniPlayer) : false,
        frequency: "frequency" in session ? String((session as any).frequency) : null,
        soundTag: "soundTag" in session ? String((session as any).soundTag) : null,
        meditationTag: "meditationTag" in session ? String((session as any).meditationTag) : null,
        ancestralTag: "ancestralTag" in session ? String((session as any).ancestralTag) : null,
        sonidosTag: "sonidosTag" in session ? String((session as any).sonidosTag) : null,
        descansoTag: "descansoTag" in session ? String((session as any).descansoTag) : null,
        themeTag: "themeTag" in session ? [...((session as any).themeTag as string[])] : null,
        sleepTag: "sleepTag" in session ? String((session as any).sleepTag) : null,
        guideId: "guideId" in session ? String((session as any).guideId) : null,
        artistId: "artistId" in session ? String((session as any).artistId) : null,
        status: "published",
        createdBy: null,
      })
      .onConflictDoNothing()
      .returning({ id: catalogSessionsTable.id });

    if (result.length > 0) {
      inserted++;
      console.log(`  ✓ [${session.id}] ${session.title}`);
    } else {
      skipped++;
      console.log(`  — [${session.id}] ${session.title} (ya existe, omitida)`);
    }
  }

  console.log(`\nFinalizado: ${inserted} insertadas, ${skipped} omitidas.`);
  await pool.end();
}

main().catch((err) => {
  console.error("Error en seed:", err);
  pool.end().finally(() => process.exit(1));
});
