// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/banner-variantes/VarianteDos.tsx": () => import("../components/mockups/banner-variantes/VarianteDos.tsx"),
  "./components/mockups/banner-variantes/VarianteTres.tsx": () => import("../components/mockups/banner-variantes/VarianteTres.tsx"),
  "./components/mockups/banner-variantes/VarianteUno.tsx": () => import("../components/mockups/banner-variantes/VarianteUno.tsx"),
  "./components/mockups/cat-palettes/Cosmos.tsx": () => import("../components/mockups/cat-palettes/Cosmos.tsx"),
  "./components/mockups/cat-palettes/Niebla.tsx": () => import("../components/mockups/cat-palettes/Niebla.tsx"),
  "./components/mockups/cat-palettes/Primavera.tsx": () => import("../components/mockups/cat-palettes/Primavera.tsx"),
  "./components/mockups/cat-palettes/TierraCAlida.tsx": () => import("../components/mockups/cat-palettes/TierraCAlida.tsx"),
  "./components/mockups/iconos/IconPicker.tsx": () => import("../components/mockups/iconos/IconPicker.tsx"),
  "./components/mockups/iconos/IconosMeditacion.tsx": () => import("../components/mockups/iconos/IconosMeditacion.tsx"),
  "./components/mockups/mixer-colores/OpcionA.tsx": () => import("../components/mockups/mixer-colores/OpcionA.tsx"),
  "./components/mockups/mixer-colores/OpcionB.tsx": () => import("../components/mockups/mixer-colores/OpcionB.tsx"),
  "./components/mockups/mixer-colores/OpcionC.tsx": () => import("../components/mockups/mixer-colores/OpcionC.tsx"),
  "./components/mockups/premium-colores/VarianteDos.tsx": () => import("../components/mockups/premium-colores/VarianteDos.tsx"),
  "./components/mockups/premium-colores/VarianteTres.tsx": () => import("../components/mockups/premium-colores/VarianteTres.tsx"),
  "./components/mockups/premium-colores/VarianteUno.tsx": () => import("../components/mockups/premium-colores/VarianteUno.tsx"),
  "./components/mockups/progreso/TuProgreso.tsx": () => import("../components/mockups/progreso/TuProgreso.tsx"),
  "./components/mockups/tab-hover/TabHover.tsx": () => import("../components/mockups/tab-hover/TabHover.tsx"),
  "./components/mockups/tab-hover/TabHover1.tsx": () => import("../components/mockups/tab-hover/TabHover1.tsx"),
  "./components/mockups/tab-hover/TabHover2.tsx": () => import("../components/mockups/tab-hover/TabHover2.tsx"),
  "./components/mockups/tab-hover/TabHover3.tsx": () => import("../components/mockups/tab-hover/TabHover3.tsx"),
  "./components/mockups/tab-hover/TabHover4.tsx": () => import("../components/mockups/tab-hover/TabHover4.tsx"),
  "./components/mockups/sesion-destacada/FrostedGlass.tsx": () => import("../components/mockups/sesion-destacada/FrostedGlass.tsx"),
  "./components/mockups/sesion-destacada/GradientEditorial.tsx": () => import("../components/mockups/sesion-destacada/GradientEditorial.tsx"),
  "./components/mockups/sesion-destacada/SplitCard.tsx": () => import("../components/mockups/sesion-destacada/SplitCard.tsx")
};
